version: "3.3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports: 
      - "8081:8081"